.gitignore, README.md, configSchema.js, configSchema.test.js, fetch.js, package-lock.json, package.json
Projects like `API`, `ORM`, `render-server`, `render-client` can be configured with a `config.js` file they load on startup.
This PR adds validation functions for separate config keys.
Usage:
```js
const { validateAPI, validateORM } = require('@datawrapper/shared/node/config-schema')
validateAPI(config.api)
validateORM(config.orm)
```
All functions write to `stderr` if a key validation fails and will exit with code 1 in that case.
Exported functions so far:
* `validateAPI`
* `validateORM`
* `validateFrontend`
* `validateRenderServer`
* `validateRenderClient`
=> feat: server config validation functions

README.md, index.js, tailLength.js, tailLength.test.js, toFixed.js
`tailLength` was already used internally in `toFixed`, it now gets imported into it instead.
=> add tailLength as separate function

.circleci/config.yml, configSchema.js, package-lock.json, package.json
Hapijs switched to scoped packages with `@hapi` scope. Since I'm moving the API to those packages
and want npm to deduplicate as much as possible, I'm going through plugins etc to move to the new packages.
=> chore: use scoped joi package

CodedError.js, CodedError.test.js, README.md, index.js
A custom Error object that allows for storing both an error code and an error message (the standard JS error only stores a message). Feel free to use this error whenever you need to cleanly separate error code from error message.
**Example**  
```js
import { CodedError } from '@datawrapper/shared';
throw new CodedError('notFound', 'the chart was not found');
```
=> add custom error class `CodedError`

package-lock.json, package.json, purifyHtml.js, purifyHtml.test.js
A customer wanted to implement a "reload" button for a table, for which he created a link with `target="_self"`. This was broken due to our implementation of link sanitzing
=> Alow target=_self if users sets explicitly

README.md, node/findConfig.js, package.json
Currently we have this code snippet in most node servers (`api`, `frontend`, `render-server`, `render-client`):
```js
const cfgPath = [path.join(process.cwd(), 'config.js'), '/etc/datawrapper/config.js'].reduce(
(path, test) => {
return path || (fs.existsSync(test) ? test : false);
},
''
);
```
It finds our `config.js` file which is usually located at `/etc/datawrapper/`. I refactored it a little to support a `DW_CONFIG_PATH` env variable and look first in the mentioned folder.
The config location is not in flux anymore and this simplifies lookup for our node apps.
=> feat: add utility functions to find and require DW config files

README.md, defaultColors.js, defaultColors.test.js
This is a function that is in use by all visualization types to define automatic colors for all themable chart elements such as labels, gridlines, bar background etc. In order to ensure that they are legible, for any given background color.
The function is already in use everywhere and this PR does not change the core functionality, however because it was originally hastily added to this repo during the transition to npm it was previously lacking documentation and tests, which this PR adds. This PR also removes the dependency on `d3-interpolate`, and adds two  features:
- Theme can define the 'base color' used for chart elements, which is then mixed with the background accordingly. If undefined, theme will decide on a light or dark one depending on the contrast to background.
- Theme can …
=> Some additions to defaultColors + readme documentation & tests

httpReq.js, httpReq.test.js
before this PR, `httpReq` would just throw a pretty useless Error with a message of `[statusCode] statusText`. Even worse, due to a bug that slipped through the statusCode in said message was always `undefined` (because it's called `res.status` instead of `res.statusCode`).
Instead, this PR introduces a new custom error object `HttpReqError` that gets initialized with the http response object and exposes some useful properties (e.g. `error.status` for the http status code) as well as the raw response object (which can be used to obtain the json body).
```js
try {
await httpReq(url, options);
} catch (error) {
if (error.name === 'HttpReqError') {
// do cool stuff
const body = await error.response.json();
logger.error(`The request returned ${error.status}`, body);
} else {
// for other …
```
=> throw more useful errors in httpReq

README.md, chart.js, httpReq.js
This PR accidentally contains two changes:
1. change the `Chart` class to no longer use `putJSON` from `fetch.js` but `httpReq.put` for storing chart changes
2. fix es6 exporting for `httpReq` so that `import { put } from 'httpReq'` works, too
=> use httpReq in chart.js

node/findConfig.js
This makes services aware of the `core` repositories config path, when `requireConfig` or `findConfigPath` are called on the host machine.
**Why?**
The new `frontend` service is running `npm run build` after installing dependencies. That means when a developer does `npm install`, the script would fail because `npm run build` can't find the config (required in `rollup.config.js`) two directories up. This is usually happening on their host machine and not inside Docker (where the config is located at `/etc/datawrapper/config.js`).
> **It would be cool if our `findConfig.js` would find the config in the core directory**
> *- Quote: David K*
=> feat: make findConfigPath aware of Docker setups

httpReq.js, httpReq.test.js
This is a small update to `httpReq`. It adds a check for whether the response contains `content-type` before trying to parse it. 
Without this additional check, there is at least one current situation which would lead to an error when using `httpReq`: [in `chart-data-s3` we return response code `201` if asset file does not exist yet](https://github.com/datawrapper/plugin-chart-data-s3/blob/df99147a0372cde067d47df789836087a1eaebdf/api.js#L64). But no content is returned and no `content-type` is set, so an error would occur here. The change in this PR fixes this.
In general, I think it's good to check whether `content-type` has actually been set before we do anything with it, no matter what response code is received.
=> Check if content-type is set in httpReq

significantDimension.js
We all know, and haven't paid much attention to this this rather ugly but otherwise mostly harmless bug, but given this is one of the first things users might see, I thought it might be time to investigate. Looks like the fix was pretty simple.
Before:
After:
=> Fix significantDimension function

formatNumber.js
Numeral has a format (X), which formats negative numbers in brackets, instead of with a minus sign
The extra logic built in to formatNumber to get unit, sign etc. in the right order, meant that this format was no longer respected.
This PR fixes that by checking for the case that a parentheses format is used and not using this special logic in that case.
I used the simple check of `format.indexOf('(') > -1` because that's how this format is checked for within numeral.js itself.
**Before:**
**After:**
=> formatNumber: Ensure that (0.0) etc. parentheses formats are respected

README.md, fetch.js, package-lock.json, package.json
`loadStylesheet(src)` currently appends a `style` tag with the given URL to `document.head`. This PR changes it so that alternatively, you can do this:
```js
loadStylesheet({
src: '...',
parentElement: someDOMNode
});
```
The existing notation continues to work and appends to `document.head`.
=> Allow to specify a parent for loadStylesheet

.github/workflows/lint-and-test.yml, package-lock.json, package.json, significantDimension.js
I think we should be using `underscore` instead of `lodash-es`, now that it's modularized.
=> remove lodash-es

package-lock.json, package.json, sportsSeasonFormat.js
https://www.notion.so/datawrapper/Season-format-for-axis-tick-labels-13fd3d7671ac47b78a51379cea534861
Original PR from Gregor: https://github.com/datawrapper/plugin-d3-lines/pull/79#issue-594819706
I slightly modified the suggestion so that the season separator (the `-` in `2005-06`) is configurable on locale level, as `2005/06` is the common Notation in German.
=> Add sports season format

sportsSeasonFormat.js
Turns out the lookbehind used in the `sportsSeasonFormat` isn't supported by safari or IE. so we will revert to SS|S which does collide with existing milliseconds format SSS, but that should be on ok sacrifice to make for now given the urgency of the bug.
=> don't use lookbehind in sportSeasonFormat

README.md, get.js, get.test.js, set.js, set.test.js
In the new map data upload, we are doing this:
``` js
chart.getMetadata(`data.column-format.${columnName}.type`);
```
But that's unsecure, because `columnName` can contain a dot.
We should rather do this:
``` js
chart.getMetadata(['data', 'column-format', columnName, 'type']);
```
Add support for the `key` argument of `get()` and `set()` to be an array of strings.
=> get,set: Support array of strings as the 'key' arg

numberColumnFormatter.js, numberColumnFormatter.test.js
For backwards-compatibility with `Globalize`, we need to include the thousand-separator in the number format
=> Include thousand separator in default number formatter

dateColumnFormatter.js, package-lock.json, package.json, significantDimension.js
There's a new ~~major~~ minor version of Underscore that changes internal path structure. This causes issues with the way we import shared files that rely on `underscore` & `@datawrapper/shared`.
This PR only upgrades underscore for this repo, which we'd have to upgrade in other projects as well. Long term we should consider defining `peerDependencies` with a specific version, or provide bundles for libs.
=> Upgrade underscore to v13.1

README.md, drawPattern.js
Adds `drawPattern` method that creates an SVG pattern `def` for a configurable pattern style, that can then be used as a `fill` on elements.
To be used by:
- `locator-maps`: https://github.com/datawrapper/plugin-locator-maps/pull/130
- `d3-bars`
=> Add drawPattern helper
